import Phaser from "phaser";
import { api, GameStateDto, HeroDto } from "../net/api";
import { claimVoucher } from "../web3/wallet";
import { registerPixelArt, blockTier } from "../art/pixelart";

const COLS = 8;
const ROWS = 5;
const TILE = 64;
const GRID_X = 240;
const GRID_Y = 90;
const POLL_MS = 2000;

const RARITY_NAMES = ["Common", "Rare", "S.Rare", "Epic", "Legend", "Mythic"];

/**
 * Main mining screen. All simulation happens on the server; this scene
 * only renders the state polled every POLL_MS and animates cosmetic
 * bombs. Placeholder art generated by code (Phase 4: original pixel art).
 *
 * Interactions: clicking a hero toggles mine/rest; clicking while holding
 * the H key houses/unhouses the hero in the first house with a free slot.
 */
export class MiningScene extends Phaser.Scene {
  private state?: GameStateDto;
  private blockSprites: Phaser.GameObjects.Image[] = [];
  private blockBars: Phaser.GameObjects.Rectangle[] = [];
  private heroRows: Phaser.GameObjects.Container[] = [];
  private pendingText!: Phaser.GameObjects.Text;
  private housesText!: Phaser.GameObjects.Text;
  private statusText!: Phaser.GameObjects.Text;
  private stageButtons: Phaser.GameObjects.Text[] = [];
  private selectedStage = 0;
  private keyH!: Phaser.Input.Keyboard.Key;
  private keyA!: Phaser.Input.Keyboard.Key;
  private pollTimer?: Phaser.Time.TimerEvent;
  private bombTimer?: Phaser.Time.TimerEvent;

  constructor() {
    super("mining");
  }

  create() {
    registerPixelArt(this);
    this.add.text(GRID_X, 24, "MINERBLAST — Treasure Mining", {
      fontFamily: "monospace",
      fontSize: "22px",
      color: "#ffb74d",
      fontStyle: "bold",
    });

    this.pendingText = this.add.text(GRID_X, 54, "loading...", {
      fontFamily: "monospace",
      fontSize: "16px",
      color: "#a5d6a7",
    });

    const market = this.add
      .text(GRID_X + 300, 50, "[ Market ]", {
        fontFamily: "monospace",
        fontSize: "16px",
        color: "#ffcc80",
        backgroundColor: "#1c2333",
        padding: { x: 10, y: 6 },
      })
      .setInteractive({ useHandCursor: true });
    market.on("pointerdown", () => this.scene.start("market"));

    const claim = this.add
      .text(GRID_X + 420, 50, "[ Claim BLAST ]", {
        fontFamily: "monospace",
        fontSize: "16px",
        color: "#4fc3f7",
        backgroundColor: "#1c2333",
        padding: { x: 10, y: 6 },
      })
      .setInteractive({ useHandCursor: true });
    claim.on("pointerdown", () => this.onClaim());

    this.statusText = this.add.text(20, 560, "", {
      fontFamily: "monospace",
      fontSize: "13px",
      color: "#90a4ae",
      wordWrap: { width: 760 },
    });

    // block grid (textures by ore hardness)
    for (let i = 0; i < COLS * ROWS; i++) {
      const x = GRID_X + (i % COLS) * TILE;
      const y = GRID_Y + Math.floor(i / COLS) * TILE;
      const img = this.add
        .image(x, y, "block-0")
        .setOrigin(0)
        .setDisplaySize(TILE - 6, TILE - 6);
      const bar = this.add.rectangle(x, y + TILE - 12, TILE - 6, 5, 0xffc107).setOrigin(0);
      this.blockSprites.push(img);
      this.blockBars.push(bar);
    }

    this.add.text(20, 70, "HEROES (click: mine/rest; H+click: house; A+click: adventure)", {
      fontFamily: "monospace",
      fontSize: "10px",
      color: "#90a4ae",
    });

    this.housesText = this.add.text(20, 430, "", {
      fontFamily: "monospace",
      fontSize: "12px",
      color: "#b0bec5",
    });

    this.keyH = this.input.keyboard!.addKey("H");
    this.keyA = this.input.keyboard!.addKey("A");

    this.refresh();
    this.pollTimer = this.time.addEvent({ delay: POLL_MS, loop: true, callback: () => this.refresh() });
    this.bombTimer = this.time.addEvent({ delay: 900, loop: true, callback: () => this.cosmeticBomb() });

    this.events.once(Phaser.Scenes.Events.SHUTDOWN, () => {
      this.pollTimer?.remove();
      this.bombTimer?.remove();
    });
  }

  private async refresh() {
    try {
      this.state = await api.state();
      this.render();
    } catch (err) {
      this.statusText.setText(`error: ${(err as Error).message}`);
      if ((err as Error).message === "session expired") this.scene.start("connect");
    }
  }

  private render() {
    if (!this.state) return;
    this.pendingText.setText(
      `pending: ${Number(this.state.pendingBlast).toFixed(4)} BLAST   maps: ${this.state.mapsCleared}`
    );

    this.state.blocks.forEach((b, i) => {
      const alive = b.hp > 0;
      const key = alive ? `block-${blockTier(b.maxHp)}` : "block-dead";
      const sprite = this.blockSprites[i];
      if (sprite.texture.key !== key) {
        sprite.setTexture(key).setDisplaySize(TILE - 6, TILE - 6);
      }
      this.blockBars[i].setVisible(alive).width = (TILE - 6) * (b.hp / b.maxHp);
    });

    this.housesText.setText(
      ["HOUSES:"]
        .concat(
          this.state.houses.map(
            (h) =>
              `${RARITY_NAMES[h.rarity]} — ${h.occupants}/${h.capacity} slots, +${h.regenBoostBps / 100}% regen`
          )
        )
        .join("\n")
    );

    this.renderStages();

    this.renderHeroes(this.state.heroes);
  }

  /** Adventure stage selection buttons (used with A+click on a hero). */
  private renderStages() {
    if (!this.state) return;
    this.stageButtons.forEach((b) => b.destroy());
    this.stageButtons = this.state.adventure.stages.map((s, i) => {
      const selected = this.selectedStage === s.id;
      const btn = this.add
        .text(
          GRID_X + i * 178,
          GRID_Y + ROWS * TILE + 14,
          `${selected ? "▶ " : ""}${s.name}\n${s.rewardBlast} BLAST · ${s.staminaCost} stam`,
          {
            fontFamily: "monospace",
            fontSize: "11px",
            color: selected ? "#ffb74d" : "#b0bec5",
            backgroundColor: "#1c2333",
            padding: { x: 8, y: 6 },
          }
        )
        .setInteractive({ useHandCursor: true });
      btn.on("pointerdown", () => {
        this.selectedStage = s.id;
        this.renderStages();
      });
      return btn;
    });
    const attempts = this.add.text(
      GRID_X,
      GRID_Y + ROWS * TILE + 62,
      `adventures today: ${this.state.adventure.attemptsToday}/10`,
      { fontFamily: "monospace", fontSize: "11px", color: "#90a4ae" }
    );
    this.stageButtons.push(attempts);
  }

  private async goAdventure(h: HeroDto) {
    try {
      this.statusText.setColor("#90a4ae").setText("expedition in progress...");
      const r = await api.adventure(h.id, this.selectedStage);
      this.state = r.state;
      this.render();
      this.statusText
        .setColor(r.success ? "#a5d6a7" : "#ef9a9a")
        .setText(
          r.success
            ? `victory in ${r.stage}! +${(r.rewardMicro / 1_000_000).toFixed(2)} BLAST (chance ${r.successChance}%)`
            : `defeat in ${r.stage} (chance was ${r.successChance}%) — half the stamina refunded`
        );
    } catch (err) {
      this.statusText.setColor("#ef9a9a").setText(`adventure: ${(err as Error).message}`);
    }
  }

  private renderHeroes(heroes: HeroDto[]) {
    this.heroRows.forEach((c) => c.destroy());
    this.heroRows = heroes.map((h, i) => {
      const y = 100 + i * 92;
      const c = this.add.container(20, y);
      const body = this.add.image(0, -4, `hero-${h.rarity}`).setOrigin(0).setScale(0.85);
      const name = this.add.text(54, 0, `${RARITY_NAMES[h.rarity]}  pwr ${h.power} spd ${h.speed}`, {
        fontFamily: "monospace",
        fontSize: "12px",
        color: "#eceff1",
      });
      const housed = h.houseId ? " ⌂" : "";
      const mode = this.add.text(
        54,
        16,
        (h.mode === "work" ? "⛏ mining" : "zZz resting") + housed,
        {
          fontFamily: "monospace",
          fontSize: "12px",
          color: h.mode === "work" ? "#a5d6a7" : "#90a4ae",
        }
      );
      const barBg = this.add.rectangle(54, 36, 130, 8, 0x263238).setOrigin(0);
      const bar = this.add
        .rectangle(54, 36, 130 * (h.stamina / h.staminaMax), 8, 0x4fc3f7)
        .setOrigin(0);
      const stamina = this.add.text(54, 48, `stamina ${h.stamina}/${h.staminaMax}`, {
        fontFamily: "monospace",
        fontSize: "11px",
        color: "#90a4ae",
      });

      const homeIcon = h.houseId
        ? this.add.image(40, 40, "house").setScale(0.6)
        : null;
      c.add([body, name, mode, barBg, bar, stamina]);
      if (homeIcon) c.add(homeIcon);
      c.setSize(190, 60);
      c.setInteractive(new Phaser.Geom.Rectangle(0, 0, 190, 60), Phaser.Geom.Rectangle.Contains);
      c.on("pointerdown", () => {
        if (this.keyA.isDown) return this.goAdventure(h);
        if (this.keyH.isDown) return this.toggleHouse(h);
        return this.toggleHero(h);
      });
      return c;
    });
  }

  private async toggleHero(h: HeroDto) {
    try {
      this.state = await api.setMode(h.id, h.mode === "work" ? "rest" : "work");
      this.render();
      this.statusText.setText("");
    } catch (err) {
      this.statusText.setText(`error: ${(err as Error).message}`);
    }
  }

  private async toggleHouse(h: HeroDto) {
    try {
      if (h.houseId) {
        this.state = await api.setHouse(h.id, null);
      } else {
        const free = this.state?.houses.find((x) => x.occupants < x.capacity);
        if (!free) {
          this.statusText.setText("no house with a free slot");
          return;
        }
        this.state = await api.setHouse(h.id, free.id);
      }
      this.render();
      this.statusText.setText("");
    } catch (err) {
      this.statusText.setText(`error: ${(err as Error).message}`);
    }
  }

  /** Cosmetic bomb on a live block — visual feedback between polls. */
  private cosmeticBomb() {
    if (!this.state?.heroes.some((h) => h.mode === "work")) return;
    const alive = this.state.blocks.map((b, i) => (b.hp > 0 ? i : -1)).filter((i) => i >= 0);
    if (alive.length === 0) return;
    const i = alive[Math.floor(Math.random() * alive.length)];
    const x = GRID_X + (i % COLS) * TILE + TILE / 2 - 3;
    const y = GRID_Y + Math.floor(i / COLS) * TILE + TILE / 2 - 3;

    const bomb = this.add.image(x, y - 20, "bomb");
    this.tweens.add({
      targets: bomb,
      y,
      duration: 300,
      ease: "Bounce.easeOut",
      onComplete: () => {
        bomb.destroy();
        const blast = this.add.circle(x, y, 6, 0xffa726).setAlpha(0.9);
        const spark = this.add.image(x, y, "spark").setScale(0.5);
        this.tweens.add({
          targets: blast,
          radius: 26,
          alpha: 0,
          duration: 350,
          onComplete: () => blast.destroy(),
        });
        this.tweens.add({
          targets: spark,
          scale: 1.6,
          angle: 90,
          alpha: 0,
          duration: 380,
          onComplete: () => spark.destroy(),
        });
      },
    });
  }

  private async onClaim() {
    try {
      this.statusText.setColor("#90a4ae").setText("issuing voucher...");
      const voucher = await api.voucher();
      this.statusText.setText("confirm the claim transaction in your wallet...");
      const tx = await claimVoucher(voucher);
      this.statusText.setColor("#a5d6a7").setText(`claim sent: ${tx}`);
      this.refresh();
    } catch (err) {
      this.statusText.setColor("#ef9a9a").setText(`claim failed: ${(err as Error).message}`);
      this.refresh();
    }
  }
}
